apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-playground-image
  namespace: tekton-pipelines
spec:
  type: image
  params:
    - name: url
      value: chechiachang/tekton-playground
      #value: gcr.io/gke-playground-0423/tekton-playground
