apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-playground-github
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/chechiachang/tekton-playground
