apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cron-binding
  namespace: tekton-pipelines
spec:
  params:
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cron-listener # Must match CronJob args
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-gitlab-triggers
  triggers:
    - name: cron-trig-housekeeper
      bindings:
      - name: cron-binding
      template:
        name: housekeeper
---
# Listener triggered by k8s CronJob
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tekton-cron-trigger
  namespace: tekton-pipelines
spec:
  schedule: "0 22 * * *"     # UTC+8 At 06:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-trigger
            image: busybox
            args: # Must match listener's service
              - wget
              - --spider
              - el-cron-listener.tekton-pipelines.svc.cluster.local:8080
          restartPolicy: Never
