apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-playground
  namespace: tekton-pipelines
spec:
  params:
    - name: git-ref
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: tekton-playground-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: tekton-playground
        params:
          - name: git-ref
            value: "$(params.git-ref)"
        resources:
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
                resources:
                  requests:
                    storage: 1Gi
