kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: tektontest.ddns.net
    http:
      paths:
      - path: /
        backend:
           serviceName: tekton-dashboard
           servicePort: 9097
