apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: delete-aged-runs
  namespace: tekton-pipelines
spec:
  params:
    - name: credential
      description: credential file to run terraform
      default: myproject-tekton-cd.json # tekton-cd
  steps:
    - name: delete-aged-runs
      image: google/cloud-sdk:slim
      script: |
        #!/usr/bin/env bash
        set -xe

        apt-get update && apt-get install -y kubectl

        gcloud auth activate-service-account tekton-admin@myproject.iam.gserviceaccount.com \
          --key-file=/var/secret/$(params.credential) --project myproject
        gcloud container clusters get-credentials its-tekton-k8s-tw-01 --zone asia-east1

        # Cleaning
        # - Delete Task will remove run records(crd) & logs(pods) from tekton. Also disable future rerun
        # - Delete Pod will be reconciled and remvoe log in Pod. But keep empty records(crd).

        DATE_LIMIT=$(date -d '-7 day' --utc "+%Y-%m-%dT%H:%M:%S")
        NAMESPACE="tekton-pipelines"

        kubectl --namespace ${NAMESPACE} \
          get pipelinerun \
          -o go-template --template '{{range .items}}{{.metadata.name}} {{.status.completionTime}}{{"\n"}}{{end}}' \
          | awk '$2 <= "'${DATE_LIMIT}'" { print $1 }' \
          | xargs --no-run-if-empty kubectl --namespace ${NAMESPACE} delete pipelinerun 

        kubectl --namespace ${NAMESPACE} \
          get taskrun \
          -o go-template --template '{{range .items}}{{.metadata.name}} {{.status.completionTime}}{{"\n"}}{{end}}' \
          | awk -v day="${DATE_LIMIT}" '$2 <= $day { print $1 }' \
          | xargs --no-run-if-empty kubectl --namespace ${NAMESPACE} delete taskrun

      volumeMounts:
        - name: &service-account-volume service-account-volume
          mountPath: /var/secret
  volumes:
    - name: *service-account-volume
      secret:
        secretName: gcp-credentials
