apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-gitlab-triggers-binding
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-gitlab-triggers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-gitlab-triggers-minimal
